### ISSUE TITLE
Jobs vs commands

### ISSUE THREAD

**Issue by till** [CircleCI-Public/cloudfoundry-orb#12]
Hi — sorry, this is a continuation of #10.

---

I got a bit confused with jobs and commands.

I am trying to use the latter — e.g. the `push` command to define my own job. Some context, or background if you will: While I can use multiple jobs (provided by the orb) in my workflow, I am unable to add them as `requires`. E.g., I want to be able to run certain actions only when a push succeeded.

Long story short, the command `push` does not seem to support `space` and `org`. Or `workspace_path` (to be able to use assets generated during build when I _push_ my application).

I looked at the source, and it seems that I need to run my own `install` command beforehand? I am just reluctant to trial and error this as the feedback cycle is kinda wishes (push to GitHub, wait for Circle, see response).

Am I trying something totally outrageous?

Thanks again!
Till

**Comment by iynere** [comment]
try giving the job a `name` & then `requires` should be fine @till 

https://circleci.com/docs/2.0/configuration-reference/#job_name-1

> Long story short, the command push does not seem to support space and org. Or workspace_path (to be able to use assets generated during build when I push my application).

correct. please see the documentation for that command: https://circleci.com/orbs/registry/orb/circleci/cloudfoundry#commands-push

> I looked at the source, and it seems that I need to run my own install command beforehand?

that sounds right! that's what the push job does: https://circleci.com/orbs/registry/orb/circleci/cloudfoundry#jobs-push

**Comment by till** [comment]
🙇 I shall try all this, thank you for your patience!
