### ISSUE TITLE
Add git repo to Orb description.

### ISSUE THREAD

**Issue by KyleTryon** [CircleCI-Public/cloudfoundry-orb#15]
Add git repo link to orb description.

Guideline: 
https://github.com/CircleCI-Public/Orb-Policies/blame/master/Orb%20Best%20Practices%20Guidelines.md#L13

**Comment by Buscedv** [comment]
I'll make sure to add this

**Comment by yihyang** [comment]
@KyleTryon I assumed this is what you wanted: https://github.com/CircleCI-Public/cloudfoundry-orb/pull/16

**Comment by eddiewebb** [comment]
Fixed in #16
